name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: sbt
      - name: Check proper code formatting
        run: sbt check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: sbt
      - name: Compile and run tests
        run: sbt test

  ci:
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    steps:
      - name: Aggregate of lint and build
        run: echo "CI passed"

